### ISSUE TITLE
About Pseudo Data Construction

### ISSUE THREAD

**Issue by csclimber** [maszhongming/UniEval#1]
Hi, thanks for the fantastic work. UniEval, a multi-dimensional evaluator, is quite useful!

However, I have failed to reproduce the operation of **pseudo data construction**.
(Section3.2 in the paper, especially for the **relevance dimension**)

It would be great if you could provide the the code for pseudo data construction, so we can easily train the UniEval model on other datasets.

**Comment by maszhongming** [comment]
I apologize for not having the time to structure the code for pseudo-data construction recently. However, I've uploaded an initial version ([pseudo_data_summ.py](https://github.com/maszhongming/UniEval/blob/main/pseudo_data_summ.py)) for your reference.
