### ISSUE TITLE
Is multiple reference supported

### ISSUE THREAD

**Issue by cloudygoose** [maszhongming/UniEval#2]
Hi, Is multiple references supported ? (e.g., for SummEval, where each sample has 10 references)
Thanks!

**Comment by maszhongming** [comment]
We are sorry that this version does not support multiple references.

UniEval can only use multiple reference summaries for evaluation in *relevance* dimension, as it is a reference-free evaluator in other dimensions for summarization. In our experiments, we used the first reference summary to calculate the score for *relevance*.

If you want to use multiple references, one possible approach is to average the scores of all 11 reference summaries in SummEval, which may get a small boost based on previous papers (CTC, BARTScore).

**Comment by cloudygoose** [comment]
Yeah that makes sense, thanks!
