### ISSUE TITLE
About Continual Learning

### ISSUE THREAD

**Issue by evi-Genius** [maszhongming/UniEval#3]
hi, it's a impressive work! But I have some questions. When training _fluency_,  what's the script would be like? Should the _model_name_or_path_ and _output_dir_  will be changed into _continual_summ_coherence_  and _continual_summ_fluency_ ? 
Also, how many samples per phase? 30000 for the _coherence_ ,36000  for _fluency_ ,42000 for _consistency_ and 48000 for _relevance_?
It's would be much helpful if you could release some script and code about it!

**Comment by maszhongming** [comment]
Thanks for your interest in our work! Yes, your understanding is right. You'll need to update both model paths, and the number of data you provided is correct.

Please note that the training steps needed may vary on the learning difficulty of the dimension. For example, achieving the best performance for *fluency* and *coherence* typically takes about 1 epoch, while for *consistency* and *relevance*, it may take less than 1 epoch.

**Comment by evi-Genius** [comment]
> Thanks for your interest in our work! Yes, your understanding is right. You'll need to update both model paths, and the number of data you provided is correct.
> 
> Please note that the training steps needed may vary on the learning difficulty of the dimension. For example, achieving the best performance for _fluency_ and _coherence_ typically takes about 1 epoch, while for _consistency_ and _relevance_, it may take less than 1 epoch.

Thanks for your reply! It's very useful!
